{
  "openapi": "3.0.0",
  "info": {
    "title": "Disease-Reports-API",
    "version": "1.0",
    "description": "This API utilises a web scraper to extract data from http://outbreaknewstoday.com/ and the Australian state government websites to generate articles, disease reports and the restriction in place for each state. This API outputs articles in JSON format and the output can be filtered by adding additional parameters to the request.",
    "contact": {
      "name": "Brickwalls Team",
      "url": "https://github.com/allenwu564/SENG3011-Brickwalls/tree/main",
      "email": "z5205003@ad.unsw.edu.au"
    },
    "termsOfService": "https://github.com/allenwu564/SENG3011-Brickwalls/tree/main"
  },
  "servers": [
    {
      "url": "https://diseasereportapi.azurewebsites.net"
    }
  ],
  "paths": {
    "/articles": {
      "parameters": [],
      "get": {
        "summary": "Get disease report by id",
        "tags": [],
        "responses": {
          "200": {
            "description": "Articles retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/article"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "url": "http://outbreaknewstoday.com/typhoid-taiwan-reports-1st-domestic-case-of-2021/",
                      "date_of_publication": "2020-03-13",
                      "headline": "Typhoid: Taiwan reports 1st domestic case of 2021",
                      "main_text": "The Taiwan CDC reported Tuesday the first domestic case of typhoid fever in the country for 2021 which is an illness and outbreak.",
                      "reports": [
                        {
                          "diseases": [
                            "typhoid"
                          ],
                          "syndrome": [
                            "fever"
                          ],
                          "event_date": "2020-03-13",
                          "locations": [
                            "Taiwan"
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "timestamp": "2021-03-17",
                      "status": 400,
                      "error": "Bad Request",
                      "message": "Invalid query, please provide both start and end dates",
                      "path": "/articles",
                      "client request": "/articles?start=20190701&end=20200901&location=Sydney&keyterms=illness"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "articles",
        "description": "This endpoint retrieves articles from within the database that will correspond to the queries. The start and end parameters are required, while the rest are optional and will allow for further filtering of results.",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "20210703",
              "minLength": 8,
              "maxLength": 8,
              "pattern": "\\d{8}"
            },
            "in": "query",
            "name": "start",
            "description": "Is the start date for the range for collecting articles",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "minLength": 8,
              "maxLength": 8,
              "pattern": "\\d{8}",
              "example": "20000101"
            },
            "in": "query",
            "name": "end",
            "description": "Is the end date for the range for collecting the articles",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "minLength": 0,
              "example": "illness,outbreak"
            },
            "in": "query",
            "name": "keyterms",
            "description": "This input contains a comma separated list of all the key terms you want to get news about. This input can be empty or omitted in the case where the user doesn’t want to restrict his search"
          },
          {
            "schema": {
              "type": "string",
              "minLength": 0,
              "example": "Sydney"
            },
            "in": "query",
            "name": "location",
            "description": "Is used to be able to search disease reports by a location name (city/country/state etc.), which is a string to be matched with the content in the disease report."
          }
        ]
      }
    },
    "/restrictions": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/state_restriction"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "state": "New South Wales",
                      "rules": [
                        {
                          "rule 1": "Wear a face mask. Wearing a mask is mandatory on public transport in the Greater Sydney, Blue Mountains, Central Coast and Wollongong areas. Children 12 years and under are exempt but encouraged to wear a face mask. Mask must be worn on the concourse, at coach/bus stops, and while travelling. Penalties will apply."
                        },
                        {
                          "rule 2": "Plan ahead and avoid travelling in the busiest times if you can. If you are not already using public transport in the peak, please do not start now. Services are already close to capacity to allow for physical distancing at these times. Off peak times are between 10am and 3pm."
                        },
                        {
                          "rule 3": "Check the capacity of services before you travel with the Trip Planner, transport apps or social media to see which services have space available to maintain physical distancing."
                        },
                        {
                          "rule 4": "Practise good personal hygiene and maintain physical distancing."
                        },
                        {
                          "rule 5": "Look for the green dots. These have been placed to show you the safest places to sit and stand."
                        },
                        {
                          "rule 6": "Observe capacity limits: physical distancing capacity limits on services means you may be asked to wait for the next service.",
                          "date effective": "2021-01-29T12:00:00Z"
                        },
                        {
                          "rule 6": "Observe capacity limits: physical distancing capacity limits on services means you may be asked to wait for the next service.",
                          "date effective": "2021-01-29T12:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "timestamp": "2021-03-17",
                      "status": 400,
                      "error": "Bad Request",
                      "message": "Invalid query, invalid states parameter value. Must be nsw, vic, act, nt, qld, sa, tas or wa. e.g. states=wa,nsw",
                      "path": "/restrictions",
                      "client request": "/restrictions?states=ils,nsw,tsa"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-restrictions",
        "description": "This endpoint retrieves restriction rules utilising the webscraper that will extract data from state government websites. The restrictions can be filtered by providing the states parameter which is optional. Passing no parameters will return all restrictions for all states. Currently only supporting Australian states (New South Wales, Victoria, Queensland, Northern Territory, Western Australia, South Australia, Tasmania and Australian Capital Territory)",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "minLength": 0,
              "example": "nsw,act,vic,nt,tas,wa,sa,qld"
            },
            "in": "query",
            "name": "states",
            "description": "Is used to filter what state restrictions that are returned. Only currently supports Australian states."
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "article": {
        "title": "article",
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          },
          "date_of_publication": {
            "type": "string"
          },
          "headline": {
            "type": "string"
          },
          "main_text": {
            "type": "string"
          },
          "reports": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "diseases": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "syndrome": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "event_date": {
                  "type": "string"
                },
                "locations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "error": {
        "title": "error",
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "string"
          },
          "status": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "client_request": {
            "type": "string"
          }
        }
      },
      "state_restriction": {
        "title": "state_restriction",
        "type": "object",
        "properties": {
          "state": {
            "type": "string"
          },
          "rules": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rule #": {
                  "type": "string"
                },
                "date effective": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "link": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "examples": {},
    "securitySchemes": {},
    "responses": {}
  }
}